// Copies the Mana icon font (Andrew Gioia, https://mana.andrewgioia.com) from the vendored
// ../mana-master checkout into the web app. Re-run after updating mana-master:
//   npm run sync:mana -w web
//
// - fonts  -> public/fonts/mana/ (woff2 + woff only; every current browser takes one of those)
// - css    -> src/styles/mana.css (upstream mana.css with the @font-face rewritten)
//
// MPlantin (also bundled upstream) is intentionally NOT copied: it's a commercial Monotype
// typeface, not covered by Mana's OFL/MIT licenses.
import { copyFile, mkdir, readFile, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const webDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const candidates = ["../mana-master/mana-master", "../mana-master"].map((p) => path.resolve(webDir, p));

let src;
for (const c of candidates) {
  try { await access(path.join(c, "css", "mana.css")); src = c; break; } catch { /* try next */ }
}
if (!src) throw new Error(`mana-master not found (looked in ${candidates.join(", ")})`);

const pkg = JSON.parse(await readFile(path.join(src, "package.json"), "utf8"));
const v = pkg.version;

const fontsOut = path.join(webDir, "public", "fonts", "mana");
await mkdir(fontsOut, { recursive: true });
for (const f of ["mana.woff2", "mana.woff"]) await copyFile(path.join(src, "fonts", f), path.join(fontsOut, f));

let css = await readFile(path.join(src, "css", "mana.css"), "utf8");
// Drop every upstream @font-face (Mana + MPlantin) and prepend our own.
css = css.replace(/@font-face\s*\{[^}]*\}\s*/g, "");
const header = `/* Mana v${v} by Andrew Gioia — https://mana.andrewgioia.com
   Font: SIL OFL 1.1 · CSS: MIT. Generated by web/scripts/sync-mana.mjs; don't edit by hand. */
@font-face {
  font-family: "Mana";
  src: url("/fonts/mana/mana.woff2?v=${v}") format("woff2"),
       url("/fonts/mana/mana.woff?v=${v}") format("woff");
  font-weight: normal;
  font-style: normal;
  font-display: block; /* icon font: never flash fallback glyphs */
}
`;
const outCss = path.join(webDir, "src", "styles", "mana.css");
await mkdir(path.dirname(outCss), { recursive: true });
await writeFile(outCss, header + css);

console.log(`mana v${v}: fonts -> ${path.relative(webDir, fontsOut)}, css -> ${path.relative(webDir, outCss)}`);
